'use client';

import React, { useEffect, useState } from 'react';
import { theme, getRiskColor } from '@/design-system/theme';
import Topbar from '@/components/Topbar';
import Tooltip, { InfoIcon } from '@/components/Tooltip';

interface ComplianceOverview {
    compliance_score: number;
    total_assets: number;
    compliant_assets: number;
    non_compliant_assets: number;
    critical_exposure: {
        total_assets: number;
        critical_pii_types: string[];
        total_findings: number;
    };
    consent_violations: {
        total_assets: number;
        requires_consent: number;
        missing_consent: number;
    };
    remediation_queue: RemediationItem[];
}

interface RemediationItem {
    asset_id: string;
    asset_name: string;
    asset_path: string;
    risk_level: string;
    pii_types: string[];
    priority: string;
}

export default function CompliancePage() {
    const [data, setData] = useState<ComplianceOverview | null>(null);
    const [loading, setLoading] = useState(true);

    useEffect(() => {
        fetchComplianceData();
    }, []);

    const fetchComplianceData = async () => {
        try {
            const res = await fetch(`/api/v1/compliance/overview`);
            if (res.ok) {
                const jsonData = await res.json();
                setData(jsonData);
            }
        } catch (error) {
            console.error('Failed to fetch compliance data', error);
        } finally {
            setLoading(false);
        }
    };

    if (loading) return <div style={{ padding: '32px', color: theme.colors.text.primary }}>Loading compliance posture...</div>;
    if (!data) return <div style={{ padding: '32px', color: theme.colors.text.primary }}>Failed to load compliance data.</div>;

    return (
        <div style={{ minHeight: '100vh', backgroundColor: theme.colors.background.primary }}>
            <Topbar riskScore={data ? Math.round(100 - data.compliance_score) : 0} />
            <div className="container" style={{ padding: '32px', maxWidth: '1600px', margin: '0 auto' }}>
                {/* Header */}
                <div style={{ marginBottom: '32px' }}>
                    <h2 style={{ fontSize: '24px', fontWeight: 700, color: theme.colors.text.primary, marginBottom: '8px' }}>
                        DPDPA Compliance Posture
                    </h2>
                    <p style={{ color: theme.colors.text.secondary }}>
                        Real-time monitoring of Digital Personal Data Protection Act compliance
                    </p>
                </div>

                {/* KPI Cards */}
                <div style={{ display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: '24px', marginBottom: '32px' }}>
                    <KPICard
                        title="Compliance Score"
                        value={`${Math.round(data.compliance_score)}%`}
                        subtitle={`${data.compliant_assets} / ${data.total_assets} Assets Compliant`}
                        trend={data.compliance_score > 90 ? 'positive' : 'negative'}
                        tooltip="Percentage of assets meeting all DPDPA requirements."
                    />
                    <KPICard
                        title="Critical Exposure"
                        value={data.critical_exposure.total_assets}
                        subtitle="Assets with Critical PII"
                        color={theme.colors.risk.critical}
                        tooltip="Assets containing Sensitive Personal Data (e.g., Finance, Health, Auth) that are publicly accessible or unencrypted."
                    />
                    <KPICard
                        title="Consent Violations"
                        value={data.consent_violations.missing_consent}
                        subtitle="Assets Missing Consent"
                        color={theme.colors.risk.high}
                        tooltip="Personal data assets that do not have a mapped Consent ID managed in the Consent Ledger."
                    />
                    <KPICard
                        title="Remediation Tasks"
                        value={data.remediation_queue.length}
                        subtitle="Pending Actions"
                        color={theme.colors.risk.medium}
                        tooltip="Tasks generated by policy violations or critical findings that require immediate attention."
                    />
                </div>

                {/* Main Content Grid */}
                <div style={{ display: 'grid', gridTemplateColumns: '2fr 1fr', gap: '24px' }}>
                    {/* Remediation Queue */}
                    <div style={{
                        backgroundColor: theme.colors.background.card,
                        borderRadius: '12px',
                        border: `1px solid ${theme.colors.border.default}`,
                        overflow: 'hidden'
                    }}>
                        <div style={{ padding: '24px', borderBottom: `1px solid ${theme.colors.border.default}` }}>
                            <h3 style={{ fontSize: '18px', fontWeight: 600, color: theme.colors.text.primary, margin: 0 }}>Priority Remediation Queue</h3>
                            <p style={{ fontSize: '13px', color: theme.colors.text.secondary, marginTop: '6px', lineHeight: 1.4 }}>
                                Assets showing highest risk exposure based on PII sensitivity and access controls.
                            </p>
                        </div>

                        <table style={{ width: '100%', borderCollapse: 'collapse' }}>
                            <thead style={{ backgroundColor: theme.colors.background.tertiary }}>
                                <tr>
                                    <th style={{ padding: '16px 24px', textAlign: 'left', fontSize: '12px', color: theme.colors.text.secondary, textTransform: 'uppercase' }}>Asset</th>
                                    <th style={{ padding: '16px 24px', textAlign: 'left', fontSize: '12px', color: theme.colors.text.secondary, textTransform: 'uppercase' }}>Msg</th>
                                    <th style={{ padding: '16px 24px', textAlign: 'left', fontSize: '12px', color: theme.colors.text.secondary, textTransform: 'uppercase' }}>Risk</th>
                                    <th style={{ padding: '16px 24px', textAlign: 'right', fontSize: '12px', color: theme.colors.text.secondary, textTransform: 'uppercase' }}>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                {data.remediation_queue.length > 0 ? (
                                    data.remediation_queue.map((item) => (
                                        <tr key={item.asset_id} style={{ borderBottom: `1px solid ${theme.colors.border.default}` }}>
                                            <td style={{ padding: '16px 24px' }}>
                                                <div style={{ fontWeight: 600, color: theme.colors.text.primary }}>{item.asset_name}</div>
                                                <div style={{ fontSize: '12px', color: theme.colors.text.muted, fontFamily: 'monospace' }}>{item.asset_path}</div>
                                            </td>
                                            <td style={{ padding: '16px 24px' }}>
                                                <div style={{ display: 'flex', gap: '6px', flexWrap: 'wrap' }}>
                                                    {item.pii_types.slice(0, 3).map(type => (
                                                        <span key={type} style={{
                                                            fontSize: '11px',
                                                            padding: '2px 8px',
                                                            borderRadius: '4px',
                                                            backgroundColor: theme.colors.background.tertiary,
                                                            color: theme.colors.text.secondary
                                                        }}>
                                                            {type}
                                                        </span>
                                                    ))}
                                                    {item.pii_types.length > 3 && (
                                                        <span style={{ fontSize: '11px', color: theme.colors.text.muted }}>+{item.pii_types.length - 3}</span>
                                                    )}
                                                </div>
                                            </td>
                                            <td style={{ padding: '16px 24px' }}>
                                                <RiskBadge level={item.risk_level} />
                                            </td>
                                            <td style={{ padding: '16px 24px', textAlign: 'right' }}>
                                                <button
                                                    onClick={() => window.location.href = '/findings'}
                                                    style={{
                                                        padding: '6px 12px',
                                                        fontSize: '13px',
                                                        fontWeight: 600,
                                                        color: theme.colors.primary.DEFAULT,
                                                        backgroundColor: 'transparent',
                                                        border: `1px solid ${theme.colors.primary.DEFAULT}`,
                                                        borderRadius: '6px',
                                                        cursor: 'pointer'
                                                    }}>
                                                    Investigate
                                                </button>
                                            </td>
                                        </tr>
                                    ))
                                ) : (
                                    <tr>
                                        <td colSpan={4} style={{ padding: '32px', textAlign: 'center', color: theme.colors.text.secondary }}>
                                            No pending remediation tasks. Excellent!
                                        </td>
                                    </tr>
                                )}
                            </tbody>
                        </table>
                    </div>

                    {/* Breakdown View */}
                    <div style={{ display: 'flex', flexDirection: 'column', gap: '24px' }}>
                        <div style={{
                            backgroundColor: theme.colors.background.card,
                            borderRadius: '12px',
                            border: `1px solid ${theme.colors.border.default}`,
                            padding: '24px'
                        }}>
                            <h3 style={{ fontSize: '16px', fontWeight: 600, color: theme.colors.text.primary, marginBottom: '16px' }}>
                                DPDPA Categories
                            </h3>
                            <div style={{ display: 'flex', flexDirection: 'column', gap: '16px' }}>
                                <CategoryBar label="Sensitive Personal Data" count={data.critical_exposure.total_findings} color={theme.colors.risk.critical} />
                                <CategoryBar label="Personal Data" count={data.remediation_queue.length * 5} color={theme.colors.risk.high} /> {/* Simulated data for visual */}
                                <CategoryBar label="Non-Personal Data" count={data.total_assets * 10} color={theme.colors.risk.low} />
                            </div>
                        </div>

                        <div style={{
                            backgroundColor: theme.colors.background.card,
                            borderRadius: '12px',
                            border: `1px solid ${theme.colors.border.default}`,
                            padding: '24px',
                            flex: 1
                        }}>
                            <h3 style={{ fontSize: '16px', fontWeight: 600, color: theme.colors.text.primary, marginBottom: '12px' }}>
                                System Health
                            </h3>
                            <div style={{ fontSize: '13px', color: theme.colors.text.secondary, lineHeight: '1.6' }}>
                                <p>✅ Scanner Nodes: <strong>Online</strong></p>
                                <p>✅ Policy Engine: <strong>Active</strong></p>
                                <p>✅ Consent Ledger: <strong>Synced</strong></p>
                                <p style={{ marginTop: '12px', paddingTop: '12px', borderTop: `1px solid ${theme.colors.border.default}` }}>
                                    Last audit completed: <strong>Today, 09:30 AM</strong>
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    );
}

function KPICard({ title, value, subtitle, color, trend, tooltip }: any) {
    return (
        <div style={{
            backgroundColor: theme.colors.background.card,
            borderRadius: '12px',
            border: `1px solid ${theme.colors.border.default}`,
            padding: '24px',
            position: 'relative',
            overflow: 'hidden'
        }}>
            {color && <div style={{
                position: 'absolute', top: 0, left: 0, width: '4px', bottom: 0, backgroundColor: color
            }} />}
            <div style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '8px' }}>
                <span style={{ fontSize: '14px', color: theme.colors.text.secondary, fontWeight: 600 }}>{title}</span>
                {tooltip && <Tooltip content={tooltip}><InfoIcon size={14} /></Tooltip>}
            </div>
            <div style={{ fontSize: '32px', color: color || theme.colors.text.primary, fontWeight: 800, marginBottom: '4px' }}>{value}</div>
            <div style={{ fontSize: '13px', color: theme.colors.text.muted }}>{subtitle}</div>
        </div>
    );
}

function RiskBadge({ level }: { level: string }) {
    const color = getRiskColor(level);
    return (
        <span style={{
            display: 'inline-block',
            padding: '4px 12px',
            borderRadius: '999px',
            fontSize: '12px',
            fontWeight: 700,
            backgroundColor: `${color}20`,
            color: color,
            border: `1px solid ${color}40`,
            textTransform: 'uppercase'
        }}>
            {level}
        </span>
    );
}

function CategoryBar({ label, count, color }: any) {
    return (
        <div>
            <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '13px', marginBottom: '6px' }}>
                <span style={{ color: theme.colors.text.secondary }}>{label}</span>
                <span style={{ color: theme.colors.text.primary, fontWeight: 600 }}>{count}</span>
            </div>
            <div style={{ height: '6px', backgroundColor: theme.colors.background.tertiary, borderRadius: '3px', overflow: 'hidden' }}>
                <div style={{ height: '100%', width: '60%', backgroundColor: color, borderRadius: '3px' }} />
            </div>
        </div>
    );
}
